# Generated by Django 5.1.15 on 2026-06-01 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Your own order reference (optional)",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("prepared", "Preparing at DHL"),
                            ("label_created", "Label created"),
                            ("shipped", "Shipped"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=80)),
                ("recipient_phone", models.CharField(blank=True, max_length=40)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("address_line1", models.CharField(max_length=120)),
                ("address_line2", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(max_length=40)),
                ("postal_code", models.CharField(max_length=16)),
                (
                    "country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2, e.g. DE", max_length=2
                    ),
                ),
                ("description", models.CharField(default="Goods", max_length=64)),
                (
                    "weight_g",
                    models.PositiveIntegerField(
                        default=100, help_text="Gross weight in grams"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "product",
                    models.CharField(
                        blank=True,
                        help_text="DPI product; blank = auto (GPT)",
                        max_length=8,
                    ),
                ),
                ("service_level", models.CharField(default="PRIORITY", max_length=16)),
                ("dpi_order_id", models.CharField(blank=True, max_length=40)),
                ("dpi_item_id", models.CharField(blank=True, max_length=40)),
                ("awb", models.CharField(blank=True, db_index=True, max_length=40)),
                (
                    "tracking_number",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("label_created_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
