# Generated by Django 5.1.15 on 2026-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("SALE_GOODS", "Sale of goods"),
                    ("GIFT", "Gift"),
                    ("COMMERCIAL_SAMPLE", "Commercial sample"),
                    ("RETURN_GOODS", "Returned goods"),
                    ("DOCUMENTS", "Documents"),
                    ("OTHERS", "Other"),
                ],
                default="SALE_GOODS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="hs_code",
            field=models.CharField(
                default="711311", help_text="HS tariff number (customs)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_country",
            field=models.CharField(
                default="BG", help_text="Country of origin (customs)", max_length=2
            ),
        ),
    ]
