# Generated by Django 5.1.15 on 2026-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_shipment_content_type_shipment_hs_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("SALE_GOODS", "Продажба на стоки"),
                    ("GIFT", "Подарък"),
                    ("COMMERCIAL_SAMPLE", "Търговска мостра"),
                    ("RETURN_GOODS", "Върнати стоки"),
                    ("DOCUMENTS", "Документи"),
                    ("OTHERS", "Друго"),
                ],
                default="SALE_GOODS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Чернова"),
                    ("prepared", "Подготвя се в DHL"),
                    ("label_created", "Етикет създаден"),
                    ("shipped", "Изпратена"),
                    ("cancelled", "Отказана"),
                    ("failed", "Неуспешна"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
