# Generated by Django 5.1.15 on 2026-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_shipment_content_type_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="address_line3",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="shipment",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Sender VAT / IOSS, e.g. 'VAT: GB365883274' (Etsy UK) or 'IOSS: IM...'",
                max_length=35,
            ),
        ),
    ]
