# Generated by Django 5.1.15 on 2026-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_shipment_address_line3_shipment_tax_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of items in the parcel"
            ),
        ),
    ]
