# Generated by Django 5.1.15 on 2026-06-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_shipment_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="net_weight_g",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Net weight of the goods only (customs); 0 = use parcel weight",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="weight_g",
            field=models.PositiveIntegerField(
                default=100, help_text="Gross weight in grams (parcel incl. packaging)"
            ),
        ),
    ]
