# Generated by Django 5.1.15 on 2026-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_shipment_net_weight_g_alter_shipment_weight_g"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="importer_tax_id",
            field=models.CharField(
                blank=True,
                help_text="Importer customs ref, e.g. 'ETSY UK VAT:GB365883274' or 'EORI: ...'",
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Sender VAT / IOSS, e.g. 'IOSS: IM1234567890'",
                max_length=35,
            ),
        ),
    ]
