# Generated by Django 5.1.15 on 2026-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_shipment_importer_tax_id_alter_shipment_tax_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="state",
            field=models.CharField(
                blank=True, help_text="State/region (optional)", max_length=40
            ),
        ),
    ]
