# Generated by Django 5.1.15 on 2026-06-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_shipment_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="contents_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
