# Generated by Django 5.1.15 on 2026-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_shipment_contents_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("SALE_GOODS", "Sale of goods"),
                    ("GIFT", "Gift"),
                    ("COMMERCIAL_SAMPLE", "Commercial sample"),
                    ("RETURN_GOODS", "Returned goods"),
                    ("DOCUMENTS", "Documents"),
                    ("OTHERS", "Other"),
                ],
                default="SALE_GOODS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prepared", "Preparing at DHL"),
                    ("label_created", "Label created"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
