"""Bilingual (BG/EN) copy for the marketing site, plus shared nav data.

Kept as plain dicts (not gettext) so the whole site stays in one editable
place and the templates read clean ``{{ t.hero_title }}`` lookups.
"""

LANGS = ("bg", "en")

TRANSLATIONS = {
    "bg": {
        "lang_label": "БГ",
        "nav_services": "Услуги",
        "nav_how": "Как работи",
        "nav_integrations": "Интеграции",
        "nav_pricing": "Цени",
        "nav_track": "Проследи",
        "nav_login": "Вход",
        "cta_quote": "Поискай оферта",
        "hero_kicker": "Доставка на пратки в цял свят",
        "hero_title": "Изпрати лесно и експресно твоите пратки в цял свят",
        "hero_sub": "Бързи доставки, конкурентни цени и интегрирана платформа "
        "за управление на всичките ти пратки от едно място.",
        "hero_cta_primary": "Започни сега",
        "hero_cta_secondary": "Проследи пратка",
        "track_title": "Проследи своята пратка",
        "track_placeholder": "Въведи номер за проследяване (напр. LY709462891DE)",
        "track_button": "Проследи",
        "stats_countries": "държави",
        "stats_parcels": "доставени пратки",
        "stats_uptime": "навременни доставки",
        "services_kicker": "Услуги",
        "services_title": "Всичко за твоите пратки на едно място",
        "service_1_title": "Международни пратки",
        "service_1_text": "Доставяме до над 220 държави чрез проследяеми пощенски "
        "услуги — бързо и на конкурентни цени.",
        "service_2_title": "Експресна доставка",
        "service_2_text": "Приоритетни услуги за чувствителни към времето пратки "
        "с проследяване от край до край.",
        "service_3_title": "Платформа за управление",
        "service_3_text": "Създавай етикети, групирай пратки в един AWB и "
        "управлявай всичко от един панел.",
        "service_4_title": "Връщания и поддръжка",
        "service_4_text": "Лесни връщания, етикети с QR код и поддръжка на "
        "български и английски.",
        "how_kicker": "Как работи",
        "how_title": "Три стъпки до изпратена пратка",
        "how_1_title": "Импортирай или въведи",
        "how_1_text": "Постави адреса или импортирай поръчки от Amazon, Etsy и др.",
        "how_2_title": "Генерирай етикет",
        "how_2_text": "Създаваме етикет 10x15 см и номер за проследяване автоматично.",
        "how_3_title": "Предай на куриера",
        "how_3_text": "Групираме пратките в един AWB — предаваш всичко наведнъж.",
        "integrations_kicker": "Интеграции",
        "integrations_title": "Интеграция със световните платформи",
        "integrations_sub": "Свържи своя магазин и импортирай поръчки автоматично.",
        "pricing_kicker": "Цени",
        "pricing_title": "Прозрачни цени без скрити такси",
        "pricing_cta": "Виж пълната тарифа",
        "plan_std_name": "Стандарт",
        "plan_std_desc": "За малки пратки до ЕС",
        "plan_std_price": "от 6,90 лв.",
        "plan_exp_name": "Експрес",
        "plan_exp_desc": "Приоритет с проследяване",
        "plan_exp_price": "от 12,90 лв.",
        "plan_biz_name": "Бизнес",
        "plan_biz_desc": "Обеми и API достъп",
        "plan_biz_price": "по договаряне",
        "quote_title": "Остави имейл и ще ти изпратим оферта",
        "quote_placeholder": "твоят@имейл.bg",
        "quote_button": "Изпрати",
        "quote_done": "Благодарим! Ще се свържем с теб скоро.",
        "footer_tagline": "Бързи и надеждни доставки на пратки в цял свят.",
        "footer_company": "Фирма",
        "footer_hours": "Работно време",
        "footer_contact": "Контакти",
        "footer_legal": "Документи",
        "footer_terms": "Общи условия",
        "footer_privacy": "Поверителност",
        "footer_rights": "Всички права запазени.",
        "track_results_title": "Статус на пратката",
        "track_not_found": "Няма намерена пратка с този номер. Провери номера и опитай пак.",
        "track_back": "Провери друг номер",
    },
    "en": {
        "lang_label": "EN",
        "nav_services": "Services",
        "nav_how": "How it works",
        "nav_integrations": "Integrations",
        "nav_pricing": "Pricing",
        "nav_track": "Track",
        "nav_login": "Log in",
        "cta_quote": "Get a quote",
        "hero_kicker": "Worldwide parcel delivery",
        "hero_title": "Send your parcels worldwide, easily and express",
        "hero_sub": "Fast delivery, competitive prices and an integrated platform "
        "to manage all your shipments from one place.",
        "hero_cta_primary": "Get started",
        "hero_cta_secondary": "Track a parcel",
        "track_title": "Track your parcel",
        "track_placeholder": "Enter a tracking number (e.g. LY709462891DE)",
        "track_button": "Track",
        "stats_countries": "countries",
        "stats_parcels": "parcels delivered",
        "stats_uptime": "on-time deliveries",
        "services_kicker": "Services",
        "services_title": "Everything for your parcels in one place",
        "service_1_title": "International parcels",
        "service_1_text": "We deliver to 220+ countries via tracked postal "
        "services — fast and at competitive prices.",
        "service_2_title": "Express delivery",
        "service_2_text": "Priority services for time-sensitive parcels with "
        "end-to-end tracking.",
        "service_3_title": "Management platform",
        "service_3_text": "Create labels, group parcels onto one AWB and manage "
        "everything from a single dashboard.",
        "service_4_title": "Returns & support",
        "service_4_text": "Easy returns, QR-code labels and support in Bulgarian "
        "and English.",
        "how_kicker": "How it works",
        "how_title": "Three steps to a shipped parcel",
        "how_1_title": "Import or enter",
        "how_1_text": "Paste an address or import orders from Amazon, Etsy and more.",
        "how_2_title": "Generate a label",
        "how_2_text": "We create a 4x6 label and a tracking number automatically.",
        "how_3_title": "Hand to the courier",
        "how_3_text": "We group parcels onto one AWB — you hand them over at once.",
        "integrations_kicker": "Integrations",
        "integrations_title": "Integrated with the world's platforms",
        "integrations_sub": "Connect your store and import orders automatically.",
        "pricing_kicker": "Pricing",
        "pricing_title": "Transparent pricing, no hidden fees",
        "pricing_cta": "See full rate card",
        "plan_std_name": "Standard",
        "plan_std_desc": "Small parcels within the EU",
        "plan_std_price": "from €3.90",
        "plan_exp_name": "Express",
        "plan_exp_desc": "Priority with tracking",
        "plan_exp_price": "from €6.90",
        "plan_biz_name": "Business",
        "plan_biz_desc": "Volume & API access",
        "plan_biz_price": "custom",
        "quote_title": "Leave your email and we'll send you an offer",
        "quote_placeholder": "you@email.com",
        "quote_button": "Send",
        "quote_done": "Thanks! We'll be in touch shortly.",
        "footer_tagline": "Fast, reliable parcel delivery worldwide.",
        "footer_company": "Company",
        "footer_hours": "Hours",
        "footer_contact": "Contact",
        "footer_legal": "Legal",
        "footer_terms": "Terms & Conditions",
        "footer_privacy": "Privacy Policy",
        "footer_rights": "All rights reserved.",
        "track_results_title": "Parcel status",
        "track_not_found": "No parcel found for that number. Check it and try again.",
        "track_back": "Track another number",
    },
}

# Marketplaces shown in the "integrations" strip (label + simple wordmark).
INTEGRATIONS = ["Amazon", "Etsy", "eBay", "Shopify", "WooCommerce", "DHL"]

# DPI products + service levels offered in the create form. These are the codes
# valid on the Marbaras account (GPT tracked, GMP untracked). Edit to match your
# contract — the value is the DPI product/serviceLevel code sent to DHL.
PRODUCTS = [
    ("GPT", "С тракинг – Стоки (GPT)"),
    ("GMM", "Без тракинг – Стоки (GMM)"),
    ("GMP", "С тракинг – Стоки, Плюс (GMP)"),
]
SERVICE_LEVELS = [
    ("PRIORITY", "Приоритет"),
    ("REGISTERED", "Препоръчана"),
]
